### PR TITLE
Rev B Routing

### PR DESCRIPTION
**Pull request by AEFeinstein**
* Routed board (freehand, fillet traces, teardrops)
* Moved headphone jack to top
* Via stitched every analog audio trace
* Matched USB trace lengths
* Silkscreen
    * Fixed silkscreen for PGM button
    * Added URL and email silkscreen to back
    * Updated rev to B
* Adjusted buttons to match gunship
* Adjusted touchpad to match gunship
* Only DRC warnings/errors are for the acrylic courtyard (N2) and USB ground pad thermals (impossible to have 2 filled connections)
* Probably other things I can't remember right now

### CODE REVIEW

**Comment by AEFeinstein** [comment]
@emilyanthony4244 & @cnlohr , review and merge at your leisure

**Comment by AEFeinstein** [comment]
@emilyanthony4244 one thing to note, this ground pin clips the acrylic now, so I'd recommend cutting a notch out of the acrylic. The other bits are just holes, so those are fine.
image

**Comment by cnlohr** [comment]
I am not sure how/why I would review? Should just submit what you have since we can't merge.

**Comment by AEFeinstein** [comment]
I mean, you could look at the branch, run DRC yourself. Check for other quirks you can think of, admire freehand rounded traces

**Comment by cnlohr** [comment]
But I don't know why you wouldn't merge and we can talk about it from there?

**Comment by AEFeinstein** [comment]
Oh, when I made the branch, merging it wasn't a foregone conclusion. I was messing around and took it tooooo far. Now it's on @emilyanthony4244 to smash that button, and the conversation ain't over until we ship something to Elecrow.

**Pull request merged**
